"""Canonical, framework-independent golf-domain source of truth."""

from .catalog import ProfileFixture, load_lies, load_profiles
from .course_adapter import AdaptedHole, METERS_TO_YARDS, adapt_hole_payload, load_course, load_hole
from .enums import (
    DecisionConfidence,
    DecisionLabel,
    DecisionReason,
    Dexterity,
    ExecutionLabel,
    LieType,
    PenaltyReason,
    PreferredMiss,
    ReliefType,
    ShotQuality,
    StrategicShotType,
    SurfaceType,
)
from .geometry import point_in_polygon, project_landing, resolve_surface, target_axes
from .models import (
    AuditModifier,
    ClubStat,
    DecisionEvaluation,
    DecisionSubscores,
    EnvironmentModifiers,
    ExecutionEvaluation,
    LieModifier,
    PenaltyRelief,
    PuttAudit,
    PuttContext,
    PuttProfile,
    PuttRead,
    PuttResultPacket,
    ResultAssessment,
    ShotAudit,
    ShotContext,
    ShotIntent,
    ShotResultPacket,
    StrategyContext,
    StrategyScorePacket,
    SurfaceRegion,
    Vec2,
)

__all__ = [
    "AuditModifier",
    "AdaptedHole",
    "ClubStat",
    "DecisionConfidence",
    "DecisionEvaluation",
    "DecisionLabel",
    "DecisionReason",
    "DecisionSubscores",
    "Dexterity",
    "EnvironmentModifiers",
    "ExecutionEvaluation",
    "ExecutionLabel",
    "LieModifier",
    "LieType",
    "METERS_TO_YARDS",
    "PenaltyReason",
    "PenaltyRelief",
    "PreferredMiss",
    "ProfileFixture",
    "PuttAudit",
    "PuttContext",
    "PuttProfile",
    "PuttRead",
    "PuttResultPacket",
    "ResultAssessment",
    "ReliefType",
    "ShotAudit",
    "ShotContext",
    "ShotIntent",
    "ShotQuality",
    "ShotResultPacket",
    "StrategicShotType",
    "StrategyContext",
    "StrategyScorePacket",
    "SurfaceRegion",
    "SurfaceType",
    "Vec2",
    "adapt_hole_payload",
    "load_course",
    "load_hole",
    "load_lies",
    "load_profiles",
    "point_in_polygon",
    "project_landing",
    "resolve_surface",
    "target_axes",
]
